### ISSUE TITLE
javascript errors

### ISSUE THREAD

**Issue by eelco2k** [eduardoribeirodev/filament-leaflet#7]
After installing the plugin i get some errors in the developer console: 

```
Uncaught ReferenceError: L is not defined
    at draw.js?v=3.1.0.0:8:96
    at draw.js?v=3.1.0.0:10:3412
(anonymous) @ draw.js?v=3.1.0.0:8
(anonymous) @ draw.js?v=3.1.0.0:10
11:30:27.515 fullscreen.js?v=3.1.0.0:131 Uncaught TypeError: leaflet.Control.extend is not a function
    at fullscreen.js?v=3.1.0.0:131:37
    at fullscreen.js?v=3.1.0.0:10:178
    at fullscreen.js?v=3.1.0.0:11:3
(anonymous) @ fullscreen.js?v=3.1.0.0:131
(anonymous) @ fullscreen.js?v=3.1.0.0:10
(anonymous) @ fullscreen.js?v=3.1.0.0:11
11:30:27.517 markercluster.js?v=3.1.0.0:1 Uncaught TypeError: Cannot read properties of undefined (reading 'extend')
    at markercluster.js?v=3.1.0.0:1:323
    at markercluster.js?v=3.1.0.0:1:163
    at markercluster.js?v=3.1.0.0:1:241
```

**Comment by eduardoribeirodev** [comment]
Hey man, i just fixed that issue in a new version, take a look.

**Comment by eelco2k** [comment]
unfortunately when upgrading to v4.2 with filamentphp v4.7.0 i now get these errors:

```
Alpine Expression Error: mapPicker is not defined

Expression: "mapPicker($wire, {"type":"field","statePath":"data.location","draggable":true,"showMarker":true,"tilesUrl":"https:\/\/tile.openstreetmap.de\/{z}\/{x}\/{y}.png","attribution":null,"zoomOffset":-1,"tileSize":512,"detectRetina":true,"rangeSelectField":"form.distance","minZoom":0,"maxZoom":28,"zoom":15,"clickable":true,"markerColor":"#3b82f6","liveLocation":false,"bounds":false,"showMyLocationButton":true,"default":{"lat":0,"lng":0},"markerHtml":"","markerIconUrl":null,"markerIconSize":[36,36],"markerIconClassName":"","markerIconAnchor":[18,36],"geoMan":{"show":false,"editable":true,"position":"topleft","drawCircleMarker":true,"rotateMode":true,"drawMarker":true,"drawPolygon":true,"drawPolyline":true,"drawCircle":true,"dragMode":true,"cutPolygon":true,"editPolygon":true,"deleteLayer":true,"color":"#3388ff","filledColor":"#cad9ec","snappable":false,"snapDistance":20,"drawText":true,"drawRectangle":true},"controls":{"zoomControl":true,"scrollWheelZoom":"center","doubleClickZoom":"center","touchZoom":"center","minZoom":0,"maxZoom":28,"zoom":15,"fullscreenControl":false}})"


livewire.js?id=0f6341c0:1137 Uncaught ReferenceError: mapPicker is not defined
    at [Alpine] mapPicker($wire, {"type":"fiel…), <anonymous>:3:16)
    at livewire.js?id=0f6341c0:1214:28
    at tryCatch (livewire.js?id=0f6341c0:1119:14)
    at evaluate (livewire.js?id=0f6341c0:1150:34)
    at Function.<anonymous> (livewire.js?id=0f6341c0:3616:17)
    at flushHandlers (livewire.js?id=0f6341c0:1325:48)
    at stopDeferring (livewire.js?id=0f6341c0:1330:7)
    at deferHandlingDirectives (livewire.js?id=0f6341c0:1333:5)
    at initTree (livewire.js?id=0f6341c0:1526:5)
    at livewire.js?id=0f6341c0:1472:7
```

and 

```
installHook.js:1 Alpine Expression Error: attach is not defined

Expression: "async () => {
            do {
                await (new Promise(resolve => setTimeout(resolve, 100)));
            } while (!$refs.map);
            attach($refs.map);
        }"

```

**Comment by eelco2k** [comment]
sorry this is not related your package. but https://github.com/dotswan/filament-map-picker. sorry.
